version: '3'

services:

  eventbus:
    image: rabbitmq:alpine

  influx:
    image: influxdb
    volumes:
    - "./app/influxdb/:/var/lib/influxdb/"

  couchstore:
    image: treehouses/couchdb
    labels:
      - "traefik.port=5984"
      - "traefik.frontend.rule=PathPrefixStrip: /couchstore"
    volumes:
      - "./app/couchdb/:/opt/couchdb/data/"

  history:
    image: brewblox/brewblox-history:develop
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  sparksimulator:
    image: brewblox/firmware-simulator:develop

  sparkey:
    image: brewblox/brewblox-devcon-spark:feature-couchdb
    depends_on:
      - eventbus
      - couchstore
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /sparkey"
    command: >
      --name=sparkey
      --device-host=sparksimulator

  spock:
    image: brewblox/brewblox-devcon-spark:feature-couchdb
    depends_on:
      - eventbus
      - couchstore
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spock"
    command: >
      --name=spock
      --simulation

  datastore:
    image: brewblox/brewblox-datastore:develop
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /datastore"
    volumes:
      - "./app/presets/ui_objects.json:/app/ui_objects.json"
    command: >
      --file ui_objects.json
      --volatile

  ui:
    image: brewblox/brewblox-ui:develop
    depends_on:
      - datastore
    volumes:
      - "./devdist:/usr/share/nginx/html"
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /"

  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost
    ports:
      - "9000:80"
      - "9001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
