version: '3'

services:

  eventbus:
    image: rabbitmq:alpine

  influx:
    image: influxdb
    volumes:
      - ./app/influxdb/:/var/lib/influxdb/

  datastore:
    image: treehouses/couchdb
    labels:
      - "traefik.port=5984"
      - "traefik.frontend.rule=PathPrefixStrip: /datastore"
    volumes:
      - ./app/couchdb/:/opt/couchdb/data/

  history:
    image: brewblox/brewblox-history:develop
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  sparksimulator:
    image: brewblox/firmware-simulator:develop
    ports:
      - "7376:7376"

  mdns:
    image: brewblox/brewblox-mdns:develop
    network_mode: host

  sparkey:
    image: brewblox/brewblox-devcon-spark:develop
    depends_on:
      - eventbus
      - datastore
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /sparkey"
    command: >
      --name=sparkey
      --device-host=sparksimulator

  spock:
    image: brewblox/brewblox-devcon-spark:develop
    depends_on:
      - eventbus
      - datastore
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spock"
    command: >
      --name=spock
      --simulation

  ui:
    image: brewblox/brewblox-ui:develop
    depends_on:
      - datastore
    volumes:
      - ./app/dist:/usr/share/nginx/html
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /"

  traefik:
    image: traefik
    command: -c /config/traefik.toml --docker --docker.domain=brewblox.local
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./app/traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock
