version: "3"

services:
  eventbus:
    image: rabbitmq:alpine

  influx:
    image: influxdb:1.7
    volumes:
      - ./dev/influxdb/:/var/lib/influxdb/

  datastore:
    image: treehouses/couchdb:2.3.1
    labels:
      - "traefik.port=5984"
      - "traefik.frontend.rule=PathPrefixStrip: /datastore"
    volumes:
      - ./dev/couchdb/:/opt/couchdb/data/

  history:
    image: brewblox/brewblox-history:develop
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  sparksimulator:
    image: brewblox/firmware-simulator:develop
    ports:
      - "7376:7376"

  mdns:
    image: brewblox/brewblox-mdns:develop
    network_mode: host

  sparkey:
    image: brewblox/brewblox-devcon-spark:develop
    restart: unless-stopped
    privileged: true
    depends_on:
      - eventbus
      - datastore
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /sparkey"
    #    volumes:
    #      - "../brewblox-devcon-spark/:/app/"
    command: >
      --name=sparkey
      --device-host=sparksimulator
  #      --skip-version-check

  spock:
    image: brewblox/brewblox-devcon-spark:develop
    privileged: true
    depends_on:
      - eventbus
      - datastore
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spock"
    #    volumes:
    #      - "../brewblox-devcon-spark/:/app/"
    command: >
      --name=spock
      --simulation
  #      --device-host=192.168.0.78
  #      --discovery=usb

  ui:
    image: brewblox/brewblox-ui:develop
    depends_on:
      - datastore
    volumes:
      # Generated by running "npm run devbuild"
      - ./dev/dist:/usr/share/nginx/html
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /"

  traefik:
    image: traefik:v1.7
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./dev/traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      -c /dev/null
      --docker
      --docker.domain=brewblox.local
      --entrypoints='name:http Address::9000 Redirect.EntryPoint:https'
      --entrypoints='name:https Address::9001 TLS:config/brewblox.crt,config/brewblox.key'
      --defaultentrypoints="http,https"
