version: '3'

services:

  eventbus:
    image: rabbitmq:alpine

  influx:
    image: influxdb:alpine
    # volumes:
    # - "./influxdb:/var/lib/influxdb"

  history:
    image: brewblox/brewblox-history:develop
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  spark:
    image: brewblox/brewblox-devcon-spark:develop
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spark"
    volumes:
      - "./mocks/config/seed_objects.json:/app/seed_objects.json"
    command:
      - "--simulation"
      - "--debug"
      - "--seed-profiles=0"
      - "--seed-objects=seed_objects.json"

  datastore:
    image: brewblox/brewblox-datastore:develop
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=PathPrefixStrip: /datastore/"
    volumes:
      - "./mocks/config/datastore.json:/app/datastore.json"
    command:
      - "--watch"
      - "datastore.json"

  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost
    ports:
      - "9000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
