version: "3.7"

services:
  eventbus:
    image: brewblox/rabbitmq:develop
    labels:
      - "traefik.port=15675"
      - "traefik.protocol=ws"
      - "traefik.frontend.rule=PathPrefix: /eventbus"

  influx:
    image: influxdb:1.8
    volumes:
      - ./dev/influxdb/:/var/lib/influxdb/

  datastore:
    image: treehouses/couchdb:2.3.1
    labels:
      - "traefik.port=5984"
      - "traefik.frontend.rule=PathPrefixStrip: /datastore"
    volumes:
      - ./dev/couchdb/:/opt/couchdb/data/

  history:
    image: brewblox/brewblox-history:develop
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  automation:
    image: brewblox/brewblox-automation:develop
    init: true
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /automation"

  sparkey:
    image: brewblox/brewblox-devcon-spark:develop
    restart: unless-stopped
    privileged: true
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /sparkey"
    volumes:
      - ./dev/simulator__sparkey:/app/simulator
    command: --name=sparkey --simulation --device-id=123456789012345678901234

  spock:
    image: brewblox/brewblox-devcon-spark:develop
    privileged: true
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spock"
    volumes:
      - ./dev/simulator__spock:/app/simulator
    command: --name=spock --simulation --device-id=432109876543210987654321

  traefik:
    image: traefik:v1.7
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./dev/traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock
    command: >-
      -c /dev/null
      --docker
      --docker.domain=brewblox.local
      --entrypoints='name:http Address::9000 Redirect.EntryPoint:https'
      --entrypoints='name:https Address::9001 TLS:config/brewblox.crt,config/brewblox.key'
      --defaultentrypoints="http,https"
