version: '3'

services:

  eventbus:
    image: rabbitmq:alpine

  influx:
    image: influxdb:alpine
    volumes:
    - "./influxdb:/var/lib/influxdb"

  history:
    image: brewblox/brewblox-history:develop
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  sparksimulator:
    image: brewblox/firmware-simulator:develop
    # volumes:
    #   - "./mocks/app/eeprom.bin:/target/brewblox-gcc/eeprom.bin"
    ports:
        - "8332"

  sparkey:
    image: brewblox/brewblox-devcon-spark:develop
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /sparkey"
    volumes:
      - "./mocks/app/:/app/"
    command: >
      --name=sparkey
      --device-host=sparksimulator
      --database=sparkey_db.json
      --config=sparkey_config.json

  spock:
    image: brewblox/brewblox-devcon-spark:develop
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spock"
    volumes:
      - "./mocks/app/:/app/"
    command: >
      --name=spock
      --simulation
      --database=spock_db.json
      --config=spock_config.json

  datastore:
    image: brewblox/brewblox-datastore:develop
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /datastore"
    volumes:
      - "./mocks/config/datastore.json:/app/datastore.json"
    command: >
      --file datastore.json
      --volatile

  ui:
    image: brewblox/brewblox-ui:develop
    volumes:
      - "./devdist:/usr/share/nginx/html"
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /"

  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost
    ports:
      - "9000:80"
      - "9001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
