defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":9000"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":9001"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/config/brewblox.crt"
        keyFile = "/config/brewblox.key"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "brewblox.local"
watch = true
